/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YmzSppi1Eh8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Authloading() {
  return (
    <div className="flex h-screen w-screen flex-col items-center justify-center bg-background">
      <div className="flex flex-col items-center justify-center space-y-8">
        <div className="flex h-24 w-24 animate-spin items-center justify-center rounded-full border-8 border-primary border-t-transparent">
          <div className="h-16 w-16 rounded-full border-8 border-primary border-t-transparent" />
        </div>
        <div className="text-muted-foreground text-2xl">Authenticating...</div>
      </div>
      <div className="flex flex-col items-center justify-center space-y-4 pt-8 hidden">
        <div className="flex h-12 w-12 animate-spin items-center justify-center rounded-full border-4 border-primary border-t-transparent">
          <div className="h-8 w-8 rounded-full border-4 border-primary border-t-transparent" />
        </div>
        <div className="text-muted-foreground">Connecting...</div>
      </div>
    </div>
  )
}
